Hamming-Code
============

**Author:** Prof. Dr.-Ing. Johann-Markus Batke

**Date:** [2024-07-03 Mi]



## Setup



In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Encodierung



Generatormatrix $\vec G$



In [1]:
N = 7
K = 4
L = N-K

P_KL = np.array([[1, 1, 0],
	         [0, 1, 1],
	         [1, 1, 1],
	         [1, 0, 1]]) #  Pruefstber.
G_KN = np.concatenate((np.eye(K), P_KL), axis=1)

Nachricht $\vec u$



In [1]:
u_K  = np.array([1, 0, 1, 0])
print(u_K)

[1 0 1 0]

Encodieren der Nachricht zum Sendewort $\vec v$



In [1]:
v_N = np.mod(u_K @ G_KN, 2).astype(int)
print(v_N)

[1 0 1 0 0 0 1]

## Kanal



Störung des Kanals als Störwort $\vec k$



In [1]:
k_N = np.array([0, 1, 0, 0, 0, 0, 0])

stören, Empfangswort $\vec r$ berechnen



In [1]:
r_N = np.mod(v_N + k_N, 2).astype(int)
print(r_N)

[1 1 1 0 0 0 1]

## Decodieren



Prüfmatrix $\vec H$



In [1]:
H_LN = np.concatenate((np.eye(L), P_KL)).astype(int)
print(H_LN)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 1 0]
 [0 1 1]
 [1 1 1]
 [1 0 1]]

Syndrom berechnen



In [1]:
s_L = np.mod(r_N @ H_LN, 2).astype(int)
print(s_L)

[0 1 0]

Syndrom in Decodiermatrix $\vec H$ suchen:



In [1]:
for l in range(L):
    if sum(s_L == H_LN[l])==L:
        print("Fehler an Stelle " + str(l) + " gefunden (gezählt ab Index 0)." )

Fehler an Stelle 1 gefunden (gezählt ab 0).